<a href="https://colab.research.google.com/github/Yogesh240901128/ppml/blob/main/skill_test_3_b_240901128ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Stock A price data (5 days × 3 features: Open, High, Low)
stockA = np.array([
[100, 105, 98],
[102, 108, 101],
[104, 110, 103],
[103, 109, 100],
[105, 111, 104]
])

# Stock B price data
stockB = np.array([
[98, 103, 96],
[101, 107, 99],
[103, 109, 101],
[102, 108, 98],
[104, 110, 102]
])

# Element-wise sum
sum_matrix = stockA + stockB

# Element-wise difference
diff_matrix = stockA - stockB

print("Stock A Data:\n", stockA)
print("\nStock B Data:\n", stockB)

print("\nElement-wise Sum:\n", sum_matrix)

print("\nElement-wise Difference:\n", diff_matrix)


Stock A Data:
 [[100 105  98]
 [102 108 101]
 [104 110 103]
 [103 109 100]
 [105 111 104]]

Stock B Data:
 [[ 98 103  96]
 [101 107  99]
 [103 109 101]
 [102 108  98]
 [104 110 102]]

Element-wise Sum:
 [[198 208 194]
 [203 215 200]
 [207 219 204]
 [205 217 198]
 [209 221 206]]

Element-wise Difference:
 [[2 2 2]
 [1 1 2]
 [1 1 2]
 [1 1 2]
 [1 1 2]]
